name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dhall-lang/setup-dhall@v4.2.0
      - run: dhall text <<< './example.dhall'
