name: Build
on: [push, pull_request]

jobs:
  build:
    name: Test examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dhall-lang/setup-dhall@v4.2.0
      - name: Install Nginx
        run: sudo apt install nginx
      - name: Run tests
        run: test.sh
